//! Minimal-but-valid package fixtures for tests.
//!
//! Exported behind the `test-util` feature so `silo-core`, `silo-server`
//! and `silo-cli` can build fixtures for all three formats without
//! needing real package files checked into the repo.

use serde_json::json;

use sha2::{Digest, Sha256};

use std::io::Write;

use crate::apk::{gzip, strip_tar_eof, tar_bytes};

/// A valid unsigned RPM with a single file in it.
pub fn build_test_rpm(name: &str, version: &str, release: &str, arch: &str) -> Vec<u8> {
    let pkg = rpm::PackageBuilder::new(name, version, "MIT", arch, "a test package")
        .release(release)
        .with_file_contents(
            "hello from silo\n",
            rpm::FileOptions::new(format!("/usr/share/{name}/hello.txt")),
        )
        .expect("add file")
        .build()
        .expect("build rpm");
    let mut buf = Vec::new();
    pkg.write(&mut buf).expect("write rpm");
    buf
}

/// A valid unsigned `.apk`, laid out the way `abuild` produces one: a
/// control gzip member holding `.PKGINFO`, followed by a data gzip member.
///
/// Two details are what make real `apk` accept this rather than rejecting
/// it as a "BAD archive":
///
/// - The control segment's tar is **truncated** (no end-of-archive
///   blocks). apk-tools reads the segments as one continuous tar stream,
///   so EOF blocks in the control segment hide the data segment entirely.
/// - `.PKGINFO` carries `datahash`, the SHA-256 of the data segment,
///   which apk verifies after extraction.
pub fn build_test_apk(name: &str, version: &str, arch: &str) -> Vec<u8> {
    // The data segment is built first because its hash goes into the
    // control segment that precedes it.
    let data = gzip(
        tar_bytes(&[
            // apk refuses to unpack a file whose parents aren't in the
            // archive, so the directories are listed explicitly.
            ("usr/", b"".as_slice()),
            ("usr/share/", b"".as_slice()),
            ("usr/share/hello.txt", b"hello from silo\n".as_slice()),
        ])
        .expect("data tar"),
    )
    .expect("gzip data");
    let datahash = hex::encode(Sha256::digest(&data));

    let pkginfo = format!(
        "# Generated by silo test fixtures\n\
         pkgname = {name}\n\
         pkgver = {version}\n\
         pkgdesc = a test package\n\
         url = https://example.com/{name}\n\
         builddate = 1700000000\n\
         packager = silo <silo@example.com>\n\
         size = 4096\n\
         arch = {arch}\n\
         license = MIT\n\
         origin = {name}\n\
         maintainer = silo <silo@example.com>\n\
         datahash = {datahash}\n"
    );

    let control_tar = tar_bytes(&[(".PKGINFO", pkginfo.as_bytes())]).expect("control tar");
    let control = gzip(strip_tar_eof(&control_tar)).expect("gzip control");

    let mut out = control;
    out.extend(data);
    out
}

/// A valid pacman package: `.PKGINFO` plus one installed file, compressed
/// with `ext` (`"zst"`, `"xz"`, or `"gz"`) — the three codecs `makepkg` has
/// shipped as its default across versions, all of which silo accepts.
///
/// `version` is the full `pkgver` field value (`[epoch:]version-release`,
/// e.g. `"1.0-1"` or `"2:1.0-1"`), matching what `.PKGINFO` actually
/// carries rather than silo's already-split `ParsedPackage` fields.
pub fn build_test_pacman(name: &str, version: &str, arch: &str, ext: &str) -> Vec<u8> {
    let pkginfo = format!(
        "# Generated by silo test fixtures\n\
         pkgname = {name}\n\
         pkgbase = {name}\n\
         pkgver = {version}\n\
         pkgdesc = a test package\n\
         url = https://example.com/{name}\n\
         builddate = 1700000000\n\
         packager = silo <silo@example.com>\n\
         size = 4096\n\
         arch = {arch}\n\
         license = MIT\n\
         depend = glibc\n\
         makedepend = cmake\n\
         checkdepend = python\n"
    );

    let tar = tar_bytes(&[
        (".PKGINFO", pkginfo.as_bytes()),
        ("usr/", b"".as_slice()),
        ("usr/share/", b"".as_slice()),
        ("usr/share/hello.txt", b"hello from silo\n".as_slice()),
    ])
    .expect("pacman package tar");

    match ext {
        "zst" => zstd::encode_all(tar.as_slice(), 0).expect("zstd-compress test package"),
        "xz" => {
            let mut encoder = liblzma::write::XzEncoder::new(Vec::new(), 6);
            encoder.write_all(&tar).expect("write xz stream");
            encoder.finish().expect("finish xz stream")
        }
        "gz" => gzip(&tar).expect("gzip-compress test package"),
        other => panic!("unsupported test compression `{other}`"),
    }
}

/// A valid `.deb`: the three-member `ar` archive `dpkg-deb` produces
/// (`debian-binary`, `control.tar.gz`, `data.tar.gz`), with a minimal but
/// complete `control` file.
///
/// `version` is the full control-file `Version` field
/// (`[epoch:]upstream_version[-debian_revision]`), matching what real
/// `.deb`s carry rather than silo's already-split `ParsedPackage` fields —
/// the same convention `build_test_pacman`'s `version` argument uses.
pub fn build_test_deb(name: &str, version: &str, arch: &str) -> Vec<u8> {
    let control = format!(
        "Package: {name}\n\
         Version: {version}\n\
         Architecture: {arch}\n\
         Maintainer: silo <silo@example.com>\n\
         Installed-Size: 4\n\
         Depends: libc6\n\
         Section: utils\n\
         Priority: optional\n\
         Homepage: https://example.com/{name}\n\
         Description: a test package\n\
         \x20end-to-end tests exercise this description\n"
    );
    let control_tar = tar_bytes(&[("control", control.as_bytes())]).expect("control.tar");
    let control_tar_gz = gzip(&control_tar).expect("gzip control.tar");

    let data_tar = tar_bytes(&[
        ("usr/", b"".as_slice()),
        ("usr/share/", b"".as_slice()),
        ("usr/share/hello.txt", b"hello from silo\n".as_slice()),
    ])
    .expect("data.tar");
    let data_tar_gz = gzip(&data_tar).expect("gzip data.tar");

    let mut out = Vec::new();
    {
        let mut builder = ar::Builder::new(&mut out);
        builder
            .append(
                &ar::Header::new(b"debian-binary".to_vec(), 4),
                "2.0\n".as_bytes(),
            )
            .expect("append debian-binary");
        builder
            .append(
                &ar::Header::new(b"control.tar.gz".to_vec(), control_tar_gz.len() as u64),
                control_tar_gz.as_slice(),
            )
            .expect("append control.tar.gz");
        builder
            .append(
                &ar::Header::new(b"data.tar.gz".to_vec(), data_tar_gz.len() as u64),
                data_tar_gz.as_slice(),
            )
            .expect("append data.tar.gz");
    }
    out
}

/// A valid npm tarball: `package/package.json` plus a README, gzipped.
pub fn build_test_npm(name: &str, version: &str) -> Vec<u8> {
    let manifest = json!({
        "name": name,
        "version": version,
        "description": "a test package",
        "license": "MIT",
        "main": "index.js",
    });
    let manifest = serde_json::to_vec_pretty(&manifest).expect("serialize package.json");

    gzip(
        tar_bytes(&[
            ("package/package.json", manifest.as_slice()),
            ("package/README.md", b"# test\n".as_slice()),
        ])
        .expect("npm tar"),
    )
    .expect("gzip npm tarball")
}
