//! Minimal-but-valid package fixtures for tests.
//!
//! Exported behind the `test-util` feature so `silo-core`, `silo-server`
//! and `silo-cli` can build fixtures for all three formats without
//! needing real package files checked into the repo.

use serde_json::json;

use sha2::{Digest, Sha256};

use crate::apk::{gzip, strip_tar_eof, tar_bytes};

/// A valid unsigned RPM with a single file in it.
pub fn build_test_rpm(name: &str, version: &str, release: &str, arch: &str) -> Vec<u8> {
    let pkg = rpm::PackageBuilder::new(name, version, "MIT", arch, "a test package")
        .release(release)
        .with_file_contents(
            "hello from silo\n",
            rpm::FileOptions::new(format!("/usr/share/{name}/hello.txt")),
        )
        .expect("add file")
        .build()
        .expect("build rpm");
    let mut buf = Vec::new();
    pkg.write(&mut buf).expect("write rpm");
    buf
}

/// A valid unsigned `.apk`, laid out the way `abuild` produces one: a
/// control gzip member holding `.PKGINFO`, followed by a data gzip member.
///
/// Two details are what make real `apk` accept this rather than rejecting
/// it as a "BAD archive":
///
/// - The control segment's tar is **truncated** (no end-of-archive
///   blocks). apk-tools reads the segments as one continuous tar stream,
///   so EOF blocks in the control segment hide the data segment entirely.
/// - `.PKGINFO` carries `datahash`, the SHA-256 of the data segment,
///   which apk verifies after extraction.
pub fn build_test_apk(name: &str, version: &str, arch: &str) -> Vec<u8> {
    // The data segment is built first because its hash goes into the
    // control segment that precedes it.
    let data = gzip(
        tar_bytes(&[
            // apk refuses to unpack a file whose parents aren't in the
            // archive, so the directories are listed explicitly.
            ("usr/", b"".as_slice()),
            ("usr/share/", b"".as_slice()),
            ("usr/share/hello.txt", b"hello from silo\n".as_slice()),
        ])
        .expect("data tar"),
    )
    .expect("gzip data");
    let datahash = hex::encode(Sha256::digest(&data));

    let pkginfo = format!(
        "# Generated by silo test fixtures\n\
         pkgname = {name}\n\
         pkgver = {version}\n\
         pkgdesc = a test package\n\
         url = https://example.com/{name}\n\
         builddate = 1700000000\n\
         packager = silo <silo@example.com>\n\
         size = 4096\n\
         arch = {arch}\n\
         license = MIT\n\
         origin = {name}\n\
         maintainer = silo <silo@example.com>\n\
         datahash = {datahash}\n"
    );

    let control_tar = tar_bytes(&[(".PKGINFO", pkginfo.as_bytes())]).expect("control tar");
    let control = gzip(strip_tar_eof(&control_tar)).expect("gzip control");

    let mut out = control;
    out.extend(data);
    out
}

/// A valid npm tarball: `package/package.json` plus a README, gzipped.
pub fn build_test_npm(name: &str, version: &str) -> Vec<u8> {
    let manifest = json!({
        "name": name,
        "version": version,
        "description": "a test package",
        "license": "MIT",
        "main": "index.js",
    });
    let manifest = serde_json::to_vec_pretty(&manifest).expect("serialize package.json");

    gzip(
        tar_bytes(&[
            ("package/package.json", manifest.as_slice()),
            ("package/README.md", b"# test\n".as_slice()),
        ])
        .expect("npm tar"),
    )
    .expect("gzip npm tarball")
}
