{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "silo.fullname" . }}-config
  labels:
    {{- include "silo.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- .Values.config | nindent 4 }}
{{- end }}
