{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "silo.fullname" . }}-config
  labels:
    {{- include "silo.labels" . | nindent 4 }}
  {{- include "silo.annotations" (dict "ctx" . "extra" (dict)) }}
type: Opaque
stringData:
  config.yaml: |
    {{- include "silo.config" . | nindent 4 }}
{{- end }}
