{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "silo.fullname" . }}
  labels:
    {{- include "silo.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- include "silo.annotations" (dict "ctx" . "extra" .Values.serviceMonitor.annotations) }}
spec:
  selector:
    matchLabels:
      {{- include "silo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
