#!/usr/bin/env bash
# One-time setup for the dev container: install the tools the build needs
# that the base image doesn't carry, and write a ready-to-use server
# config.
#
# Idempotent — the editor re-runs postCreateCommand whenever the container
# is rebuilt, and every step here tolerates having been done already.
set -euo pipefail

cd "$(dirname "$0")/.."

# The cargo registry and target directories are named volumes, which
# Docker creates owned by root. Nothing else fixes this: the base image's
# ownership is applied when the image is built, not when a volume is
# mounted over the path afterwards.
echo "==> claiming the cache volumes"
sudo chown -R "$(id -u):$(id -g)" "${CARGO_HOME:-/usr/local/cargo}/registry" /workspace/target 2>/dev/null || true

echo "==> installing build dependencies"
# protoc is the only non-Rust build dependency: silo-proto's build.rs
# compiles the .proto files at build time rather than checking generated
# code into the tree.
export DEBIAN_FRONTEND=noninteractive
sudo -E apt-get update -qq
sudo -E apt-get install -y --no-install-recommends protobuf-compiler jq >/dev/null

echo "==> installing rust components"
rustup component add rustfmt clippy >/dev/null 2>&1 || true

# Nothing here waits for SeaweedFS or creates the bucket. The compose file
# has this container depend on its `createbucket` service completing, so
# by the time any of this runs the bucket already exists — and the base
# image never needs an S3 client of its own to make one.

echo "==> writing .devcontainer/config.yaml"
# Not the repo's config.example.yaml verbatim: that one points at the
# service names the root docker-compose.yaml uses. This points at the
# sibling services in *this* compose file and binds to all interfaces so
# the editor's port forwarding can reach it.
cat > .devcontainer/config.yaml <<'EOF'
# Generated by .devcontainer/setup.sh. Safe to edit; it is gitignored.
grpc_addr: "0.0.0.0:9090"
http_addr: "0.0.0.0:8080"

database:
  url: "postgres://silo:silo@postgres:5432/silo"

storage:
  bucket: "silo"
  region: "us-east-1"
  access_key_id: "siloadmin"
  secret_access_key: "siloadmin"
  endpoint: "http://seaweedfs:8333"
  allow_http: true

auth:
  bootstrap: true
  allow_anonymous_read: false

audit:
  log_downloads: true
  retention_days: 90

metrics:
  enabled: true
  require_auth: false
EOF

echo "==> warming the build cache"
# Dependencies only, so the first real `cargo test` is quick without this
# step itself taking as long as a full build.
cargo fetch --quiet
cargo build --workspace --features silo-core/test-util,silo-pkg/test-util \
    2>&1 | tail -3 || true

cat <<'EOF'

  silo dev container is ready.

    cargo test --workspace --features silo-core/test-util,silo-pkg/test-util
    cargo clippy --workspace --all-targets --features silo-core/test-util,silo-pkg/test-util -- -D warnings

  Run the server (its bootstrap admin password prints once, on first start
  against an empty database):

    SILO_CONFIG=.devcontainer/config.yaml cargo run -p silo-server

  Then, in another terminal:

    cargo run -p silo-cli -- login --username admin
    cargo run -p silo-cli -- version

  Postgres is `postgres:5432`, SeaweedFS serves S3 on `seaweedfs:8333`
  (siloadmin/siloadmin) with the filer's web UI on 8888 — browse the
  bucket under /buckets/silo. Both are forwarded to your host.

EOF
